WINDOW_WIDTH = 1280;
WINDOW_HEIGHT = 720;

VIRTUAL_WIDTH = 512;
VIRTUAL_HEIGHT = 288;

BG_WIDTH = 256;
BG_HEIGHT = 128;

TILE_WIDTH = 16;
TILE_HEIGHT = 16;

CHAR_WIDTH = 16;
CHAR_HEIGHT = 20;

GRID_ROWS = VIRTUAL_HEIGHT / TILE_HEIGHT;
GRID_COLS = VIRTUAL_WIDTH / TILE_WIDTH;

CAMERA_SCROLL_SPEED = 90;

ALIEN_SPEED = 90;

OFF_SET = 2;